---
name: atmos-runner

on:
  issue_comment:
    types: [created, edited]

jobs:
  atmos-plan:
    if: contains(github.event.comment.html_url, '/pull')
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: checkout scm
        uses: actions/checkout@v4

      - name: install terraform
        uses: hashicorp/setup-terraform@v2

      - name: setup atmos
        uses: cloudposse/github-action-setup-atmos@v1

      - name: run atmos
        id: atmos-run
        if: startsWith(github.event.comment.body, 'atmos workflow')
        run: ${{ github.event.comment.body }}

      - name: update pr with comments
        uses: actions/github-script@v6
        env:
          PLAN: "terraform\n${{ steps.atmos-run.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `## Atmos plan

              #### Atmos status \`${{ steps.atmos-run.outputs.exitcode }}\`

              <details><summary>Show Atmos plan</summary>

              \`\`\`\n
              ${process.env.PLAN}
              \`\`\`

              </details>
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
