---
name: infrastructure-ci

on:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: checkout scm
        uses: actions/checkout@v4

      - name: install terraform
        uses: hashicorp/setup-terraform@v2

      - name: setup atmos
        uses: cloudposse/github-action-setup-atmos@v1

      - name: run atmos
        id: atmos-run
        run: atmos workflow plan-all-runners --file runners

      - run: echo "${{ steps.atmos-run.outputs.stdout }}"
      - run: echo "${{ steps.atmos-run.outputs.stderr }}"
      - run: echo "${{ steps.atmos-run.outputs.exitcode }}"
